export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REDMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const SET_INGREDIENT="SET_INGREDIENT";
export const SET_INGREDIENT_FAILED="SET_INGREDIENT_FAILED";

export const PURCHASE_BURGER_SUCCESS=" PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL=" PURCHASE_BURGER_FAIL";

export const PURCHASE_LOADING ="PURCHASE_LOADING"

export const PURCHASED ="PURCHASED"


export const PURCHASE_ORDER_SUCCESS=" PURCHASE_ORDER_SUCCESS";
export const PURCHASE_ORDER_FAIL=" PURCHASE_ORDER_FAIL";
export const ORDER_START="ORDER_START"

export const AUTH_START="AUTH_START"
export const AUTH_FAIL="AUTH_FAIL"
export const AUTH_SUCCESS="AUTH_SUCCESS"

export const AUTH_LOGOUT='AUTH_LOGOUT'

export const SET_AUTH_PATH="SET_AUTH_PATH"

